"""updated datetime fo business

Revision ID: 6d4c5d7c82b8
Revises: 4ae7f87d4034
Create Date: 2023-12-07 15:09:38.182946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d4c5d7c82b8'
down_revision: Union[str, None] = '4ae7f87d4034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
