"""edited relationships - test1

Revision ID: 7e87ecab663e
Revises: 6d4c5d7c82b8
Create Date: 2023-12-07 20:27:28.423214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e87ecab663e'
down_revision: Union[str, None] = '6d4c5d7c82b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
